# Attacker extracts sensitive data
---
- name: ING | Check for sensitive data in the readable logs.
  find:
    paths: /
    file_type: file
    recurse: yes
    hidden: yes
    patterns: 
      - '(?i)^.*{{ application }}.*\.logs$'
    use_regex: yes
    contains: '^(.*firstname|.*user|.*pass|.*address|.*street|.*lastname|.*postcode|.*account|.*creditcard|.*surname|.*iban|.*phone|.*ntlm|.*hash|.*key)'
       
  register: secret_app_logs
  check_mode: yes
  ignore_errors: yes
 
- set_fact: 
    app_secret_logs: "{{ secret_app_logs.files | to_json | from_json |json_query(\"[].{gr_name: gr_name, mode: mode, path: path }\") }}"

- debug:
    var: app_secret_logs
  run_once: True








