# Attacker steals and reuses credentials and continues lateral movement
---
- name: ING | Check sensitive files for secrets
  find:
    paths: /
    file_type: file
    recurse: yes
    contains: '^(.*firstname|.*user|.*pass|.*address|.*street|.*lastname|.*postcode|.*account|.*creditcard|.*surname|.*iban|.*phone|.*ntlm|.*hash|.*key|.*password)' 
    patterns: 
      - '*.xml'
      - '*.inc'
      - '*.db'
      - '*.py'
      - '*.sh'
      - '*.php'
      - '*.cfg'
      - '*.properties'
      - '*.java'
      - '*.log'
      - '*.config'
      - '*.conf'
      - '*.jar'
      - '*.war'  
      - '*.conf'      
  register: read_secret
  check_mode: yes
  ignore_errors: yes
 
#- set_fact: 
#    readable_file_secrets: "{{ read_secret.files | to_json | from_json |json_query(\"[?ends_with(mode, '4') == `true`|| ends_with(mode, '5') == `true`|| ends_with(mode, '6') == `true`||ends_with(mode, '7') == `true`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_secrets: "{{ read_secret.files | to_json | from_json |json_query(\"[].{gr_name: gr_name, mode: mode, path: path }\") }}"


- set_fact: 
    readable_file_non_usr: "{{ readable_file_secrets | to_json | from_json |json_query(\"[?starts_with(path, '/usr/') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_non_run: "{{ readable_file_non_usr | to_json | from_json |json_query(\"[?starts_with(path, '/run/') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_non_tmp: "{{ readable_file_non_run | to_json | from_json |json_query(\"[?starts_with(path, '/tmp/') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_non_etc: "{{ readable_file_non_tmp | to_json | from_json |json_query(\"[?starts_with(path, '/etc/') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_non_var: "{{ readable_file_non_etc | to_json | from_json |json_query(\"[?starts_with(path, '/var/') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    readable_file_non_ansible: "{{ readable_file_non_var | to_json | from_json |json_query(\"[?starts_with(path, '/home/osboxes/.') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"

- set_fact: 
    log: "{{ readable_file_non_ansible | to_json | from_json |json_query(\"[?ends_with(path, 'log') == `false`].{gr_name: gr_name, mode: mode, path: path }\") }}"



- debug:
    var: log
  run_once: True







